language: python
# List of Python versions to test
matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
# Python 3 are allowed to fail because it is not supported at this moment
  allow_failures:
    - python: 3.4
    - python: 3.5
# command to the requirements
install:
  - pip install -r config/requirements.txt
# command to run tests
script: python manage.py test --settings settings.travis
