language: python
# List of Python versions to test
matrix:
  fast_finish: true
  include:
    - python: 3.5
    - python: 3.7
  allow_failures:
    - python: 3.7
# Cache pip packages for us so builds are faster
cache: pip
# We want to use MySQL
services:
  - mysql
# Create databases before installing alexia
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xmlsec1
  - mysql -e 'CREATE DATABASE alexia_test;'
  - mysql -e 'CREATE DATABASE test_alexia_test;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON alexia_test.* to 'travis'@'%';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test_alexia_test.* to 'travis'@'%';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
# Set django settings module in environment variable
env:
  global:
    - DJANGO_SETTINGS_MODULE=alexia.conf.settings.test
# Install the requirements during installation step
install:
  - pip install -r config/requirements.txt
# command to run tests
script: python manage.py test --keepdb
